### ISSUE TITLE
Error (3999): TradeAllowed: Trade is not allowed at the moment, check the settings!

### ISSUE THREAD

**Issue by codeitlikemiley** [EA31337/EA31337#131]
I tried to run it on demo account , 
I just use the latest release out of the box,
anything i may have missed?

**Comment by kenorb** [comment]
Yes, you need to check the terminal settings.

Probably you need to enable _AutoTrading_ button in the Terminal top bar?
<img width="93" alt="Screenshot 2019-06-12 at 14 20 27" src="https://user-images.githubusercontent.com/266306/59354580-499b6700-8d1d-11e9-930f-b04236cb58e1.png">

Otherwise, make sure you're dragged and dropped into the right chart. Some brokers have like `EURUSD.micro` or something , instead of `EURUSD`.

**Comment by belazi** [comment]
I tried run Lite v1.078
The installation instructions ask you to fill in email and serialkey. How do I get Serial?
My Status: NOT ACTIVE

**Comment by kenorb** [comment]
> I tried run Lite v1.078
> The installation instructions ask you to fill in email and serialkey. How do I get Serial?
> My Status: NOT ACTIVE

See: https://github.com/EA31337/EA31337/issues/180#issuecomment-578088912

**Comment by kenorb** [comment]
> I tried run Lite v1.078

New version has been released: [v1.079](https://github.com/EA31337/EA31337/releases/tag/v1.079), please have a go.
