### ISSUE TITLE
Indi_OBV: array out of range; Zero divide in Account.mqh

### ISSUE THREAD

**Issue by sensinsane** [EA31337/EA31337#245]
2021.02.23 19:53:02.086	Core 4	genetic pass (0, 280) tested with error "critical runtime error 565 in OnTick function (error code 565, module Experts\EA31337-Advanced-v2.000.ex5, file 65535, line 1, col 1)" in 0:00:00.017

**Comment by sensinsane** [comment]
2021.02.23 19:57:26.506	Core 4	pass 1024 tested with error "critical runtime error 502 in OnTick function (array out of range, module Experts\EA31337-Advanced-v2.000.ex5, file Indi_OBV.mqh, line 133, col 16)" in 0:00:01.480
2021.02.23 19:57:28.578	Core 8	pass 5120 tested with error "critical runtime error 503 in OnTick function (zero divide, module Experts\EA31337-Advanced-v2.000.ex5, file Account.mqh, line 165, col 16)" in 0:00:03.555

**Comment by kenorb** [comment]
Thanks for the reporting.

> Indi_OBV: array out of range

I've found already the issue, it's related to OBV indicator, it's going to be fixed in the next release. Refs: https://github.com/EA31337/EA31337-classes/issues/440

> zero divide, file Account.mqh, line 165, col 16

It means either your [available margin or margin used is zero](https://github.com/EA31337/EA31337-classes/blob/v2.000/Account.mqh#L165) which is pretty unexpected.

Which symbol are you testing on?
