### ISSUE TITLE
How to pick & prioritize optimization parameters since we can't simply do all of them at once.

### ISSUE THREAD

**Issue by enjoysmath** [EA31337/EA31337#285]
I've been experimenting for 3days with the optimization parameters in strategy tester of MT5 on the EA37337.  I've tried many different orderings and number of parameters each iteration through the process.  We can't simply select all because combinatorially not even a super computer could get through the optimization step before the universe implodes (or something like that).  

So how do you recommed we perform optimization / backtesting having designed the tool?

**Comment by kenorb** [comment]
I usually optimize one set of params per run, not all of them at once. Also I think fast genetic algoritm could skip some of the good results.

Since all version are slightly different, the following personal recommendations applies to v2.005.

### General

General optimization notes:

- Recommended platform for optimization is MT5 (which is significantly better, quicker, and has better tick processing), not MT4 (older, and no longer supported).
- Default broker tick data from MT5 is more reliable than MT4 data downloaded from _History center_ (not reliable).
- For reliable backtesting/optimization in MT4, see: [Backtesting](https://github.com/EA31337/EA31337/wiki#backtesting). Basically you need to download tick data from broker and convert it to FXT/HST formats.
- Results: Note that results for MT5 can be different to MT4 due to different ticks, testing algorithms, differences in indicator implementations, broker data and settings, and many more variables. If you're optimizing for both platforms, pick top 5 from the MT5, then verify these in MT4.
- Results: Don't pick strategies which generated lesser trades (like less than 100) despite of the higher profit factor. I would rather choose strategy with 1000+ trades with lesser profit factor for its statistical reliability and proven consistency, than the one with 100 trades with higher profit factor (in this case try to increase the period).
- Always compare or confirm the final setup with _Every tick_ modelling (not OHLC), as the results can be different.

### Lite

Optimization from scratch:

- Optimize strategies per one timeframe at a time, and disable all other timeframes, e.g. optimize Strategy_H1, then H4, then M30, and so on. In this case you've 30+ interaction per run, in MT5 with 32+ CPU cores, it'll run all tests at once. Recommended period: 2020-2021.
- Combine all selected strategies and re-run. Avoid enabling strategies lesser than M15.
- Tweak results by optimizing strategies per one timeframe and how they work together (M15 and beyond).
- Consider adding M5, then M1 strategy (not recommended at the moment).

### Advanced

Optimization from scratch:

1. Reset filters to optimal defaults (to avoid unnecessary influence by external factors):

    - SOFM (Signal **Open** Filter Method) reset to 32 (which is average best).
    - SCF (Signal **Close** Filter) to 0 (disable).
    - SOTF (Signal Open **Time** Filter) to average best (e.g. 12).
    - SOSF (Signal Open **Strategy** Filter) to 0
    - TFM (**Tick** Filter Method) it depends, but never set it to 0 (it's a mess to not try to filter ticks). If you're optimizing on 1 min OHLCs, set to 32 (open prices), when optimizing by using _Every tick_ modelling, you can pick 7 (ticks at peak).
    - Tasks: Disable all
    - OCL/OCP (Order Close **Loss**/**Profit**): 0, but not required (you can set something here).
    - OCT (Order Close **Time**) recommended to -30 or -40 (number of bars to close). This avoids orders being opened for too long (e.g. profit from order based on M15 signal running for few days or weeks is merely based a luck, not technical signals).

2. Sets all Strategies and Stops to (None). And start optimizing strategies per timeframe.
3. First optimize strategies on H1, then H4 (disabling H1) to see how they perform individually (recommended period: 2020-2021).
4. Then optimize their stops for corresponding timeframes: H1 stops for H1 strategy, H4 stops for H4 strategy.
5. To optimize strategies on minute-based timeframes, you have two choices: SOSF (Strategy filter) is set to 0, or to 2.
6. When you decide on SOSF=0, you can further optimize using strategies per timeframe (and disabling other).
7. When you decide on SOSF=2, then minute-based strategies are influenced by hourly-based strategies (are opened when hourly signals are also confirmed), so keep optimizing minute-based per timeframe at a time, but having H1 and H4 strategies with their stops enabled all the time.
8. When SOSF=2, you can safely optimize strategies lesser than M15, for SOSF=0 optimizing M1-M5 are not recommended (it's going to create a random noise and influencing higher timeframe strategies by using your margin).
9. Once you selected your active strategies and their stops, re-test all strategies at once how they "play" together. It's important, as one strategies which generates too many trades can obscure and influence other strategies with lesser trades (by using safe margin) plus other factors.
10. Compare results with different modelling: Every tick vs 1 minute OHLC vs Real ticks. If tick modelling is worser than OHLC, try optimizing Tick filter method (currently 7 is recommended). But remember, playing with tick filter is like playing with a fire (it's unpredictable). If you need simple consistency, you can just use open ticks for now (=32). When optimizing in MT5 for MT4 run, compare the results between platforms as well, and find the average best configuration.
11. You can try to polish strategies by running all at once and optimizing one strategy or tops timeframe per test (selecting multiple params is a waste of resources). To save time, you can do that after filters are optimized.
12. Next, optimize strategy filters (one param and its range per test). Recommended order: SOTF, SOFM, SCF. You can repeat some of the params again, after changing the other filters.

    - SOTF: -255 to 255 (for quicker test: 0-64)
    - SOFM: -127 to 127 (for quicker test: 0-63 or 31-63)
    - SCF: -127 to 127 (for quicker test: 0-63)

13. Next, optimize Close loss/profit (e.g. 0-300 with step 20), then Close time (e.g. 0 to -50 with step -10). These params can be used with genetic algorithm.
14. Tasks should be optimized at the end. Equity based conditions are not recommended when account is used by multiple EAs. You can optimize by combining conditions and actions together.
15. Next, risk management from 1 to 10.
16. Final touch can be re-optimizing/improving individual strategies or filters per run.
17. Re-test using longer periods (2019-2021). Earlier years doesn't need to be profitable.

### Rider

Optimization from scratch (recommended period: 2019-2021):

1. Similar process to Advanced, reset all filters to their optimal defaults (don't over complicate filters at the first step, they need to stay simple to not influence strategies main logic).
2. Set 1st task: Eq.>1% then Close orders in profit. 2nd task it's up to you (you can disable or set Eq. <%5, close in not trend). This is our main logic to close orders only when we're in profit.
3. Set some default, optimal stop as a start (e.g. MA on H2). This will apply to all strategies.
4. For RIder, it's recommended to set SOSF=2.
4. Optimize strategies per timeframe at a time (disabling all other). E.g. strategies on H1, and disable all other timeframes.
5. Strategies timeframe recommended optimization order: H1, H4, M30, M15, M5, M1.
6. Re-test all strategies how they run together.
7. Optimize strategies by selecting better one (one per timeframe), once other are still running.
8. Re-optimize strategy stops and its timeframe (can be optimized together). Timeframe range (for quicker run): H1 to D1.
8. Re-optimize tasks.
9. Re-optimize filters.
10. Compare results with different tick modellings (OHLC vs Every ticks) and between different platforms (if required).
11. Re-test using longer periods (2018-2021). Earlier years doesn't need to be profitable, it's just to check how EA deals with risk management for unknown periods (to which was not optimized for).
