### ISSUE TITLE
Trades sometimes created with no magic number

### ISSUE THREAD

**Issue by francobritannique** [EA31337/EA31337#366]
Occasionally EA31337 creates trades without a magic number, which seems to result in those trades never being closed. This behaviour does not appear to be associated with a particular strategy or timeframe, as I have seen the same strategy/timeframe/pair have trades both with and without magic number.

**Comment by kenorb** [comment]
Thanks for the report.
Somebody reported similar thing with AMA strategy, that it created a position without magic number.
I'll check if there is any bug.

**Comment by francobritannique** [comment]
The most recent example I saw was Pinbar, but Pinbar also created trades _with_ a magic number, so I suspect it isn’t related to the particular strategy, but is somewhere else in the code.

**Comment by kenorb** [comment]
I was able to reproduce it while testing on live.
It's possible it was losing during modification of the order, logically if request.magic is not specified, it should leave it alone unmodified. I could only reproduce it on live, not during backtesting.
Potentially it's fixed in https://github.com/EA31337/EA31337-classes/commit/98c49a99da1bc5fea82bf472931d004450f8bbfa (it's going to be part of the next release).
I'll test it for few more days on live and see if that's fixed now.

**Comment by francobritannique** [comment]
Great - let's hope!

**Comment by kenorb** [comment]
Please try v2.013, it has several fixes, so all orders should have the right magic number.

However I've noticed in some brokers, sometimes orders aren't closed properly and stay opened, but it's going to be fixed in the separate issue at GH-372 in the next releases. This usually happens when order failed to close and EA is not retrying to close the order again.

**Comment by kenorb** [comment]
Related order bugs have been fixed in [v2.013.1](https://github.com/EA31337/EA31337/releases/tag/v2.013.1), it's advised to update.

Related: 
- <https://github.com/EA31337/EA31337-classes/issues/705>
- <https://github.com/EA31337/EA31337-classes/issues/707>
